CREATE DATABASE EMPLOYEE;
CREATE TABLE EMPLOYEE.EMP_RECORD_TABLE ( EMP_ID VARCHAR(45), FIRST_NAME VARCHAR(45), LAST_NAME VARCHAR(45), 
GENDER CHAR(1), ROLE VARCHAR(45), DEPT VARCHAR(45),
EXP INT, COUNTRY VARCHAR(45), CONTINENT VARCHAR(45), 
SALARY INT, EMP_RATING INT, MANAGER_ID VARCHAR(45), 
PROJ_ID VARCHAR(45));
CREATE TABLE EMPLOYEE.PROJ_TABLE ( PROJ_ID VARCHAR(45), PROJ_NAME VARCHAR(45), DOMAIN VARCHAR(45), 
START_DTAE DATETIME, CLOSURE_DATE DATETIME, DEV_QTR VARCHAR(45),  
STATUS VARCHAR(45));
CREATE TABLE EMPLOYEE.DATA_SCIENCE_TABLE ( EMP_ID VARCHAR(45), FIRST_NAME VARCHAR(45), LAST_NAME VARCHAR(45), 
GENDER CHAR(1), ROLE VARCHAR(45), DEPT VARCHAR(45),
EXP INT, COUNTRY VARCHAR(45), CONTINENT VARCHAR(45));
SELECT*FROM EMPLOYEE.EMP_RECORD_TABLE;
SELECT*FROM EMPLOYEE.DATA_SCIENCE_TABLE;  
ALTER TABLE EMPLOYEE.PROJ_TABLE CHANGE START_DTAE START_DATE DATETIME;
ALTER TABLE EMPLOYEE.PROJ_TABLE MODIFY START_DATE DATE, MODIFY CLOSURE_DATE DATE;
SELECT*FROM EMPLOYEE.PROJ_TABLE;
SELECT EMP_ID, FIRST_NAME,LAST_NAME,GENDER,DEPT FROM EMPLOYEE.EMP_RECORD_TABLE;
SELECT EMP_ID, FIRST_NAME,LAST_NAME,GENDER,DEPT,EMP_RATING FROM EMPLOYEE.EMP_RECORD_TABLE
WHERE EMP_RATING < '2';
SELECT EMP_ID, FIRST_NAME,LAST_NAME,GENDER,DEPT,EMP_RATING FROM EMPLOYEE.EMP_RECORD_TABLE
WHERE EMP_RATING > '4';
SELECT EMP_ID, FIRST_NAME,LAST_NAME,GENDER,DEPT,EMP_RATING FROM EMPLOYEE.EMP_RECORD_TABLE
WHERE EMP_RATING BETWEEN '2' AND '4';
SELECT CONCAT(FIRST_NAME,' ' ,LAST_NAME) NAME FROM EMPLOYEE.EMP_RECORD_TABLE WHERE DEPT = 'FINANCE';
SELECT MIN(SALARY) AS MIN_SALARY, MAX(SALARY) AS MAX_SALARY, DEPT FROM EMPLOYEE.EMP_RECORD_TABLE GROUP BY DEPT;
SELECT MAX(EMP_RATING) AS EMP_RATING, EMP_ID,FIRST_NAME,LAST_NAME,ROLE,DEPT FROM EMPLOYEE.EMP_RECORD_TABLE GROUP BY DEPT;
SELECT FIRST_NAME,LAST_NAME,COUNTRY,SALARY FROM EMPLOYEE.EMP_RECORD_TABLE WHERE SALARY > '6000';
CREATE VIEW EMPLOYEE.EMP_SALARY AS
SELECT FIRST_NAME,LAST_NAME,COUNTRY,SALARY
FROM EMPLOYEE.EMP_RECORD_TABLE
WHERE SALARY > '6000';

SELECT*FROM EMPLOYEE.EMP_SALARY;
SELECT*FROM EMPLOYEE.EMP_RECORD_TABLE
WHERE EXP > '10';
DELIMITER $$
CREATE PROCEDURE EMPLOYEE.GET_EMP_EXP ()
BEGIN
SELECT*FROM EMPLOYEE.EMP_RECORD_TABLE
WHERE EXP > "3";
END $$
CALL EMPLOYEE.GET_EMP_EXP ();
UPDATE TABLE EMPLOYEE.EMP_RECORD_TABLE SET SALARY = SALARY*0.05*EMP_RATING
END;
